### PR TITLE
Use LazyLock over lazy_static

### PR DESCRIPTION
**Pull request by atezet**
This would need an MSRV of 1.80.0 so it might have to wait a bit.

Sorry for the formatting changes, if you'd consider merging this I'm happy to revert those.

EDIT: it's also fine to only use the docs + test (as they already work perfectly)

### CODE REVIEW

**Comment by greyblake** [comment]
@atezet Thanks for the PR!

Yes, could you please revert the formatting changes in the README and docs?

`LazyLock` is the long term way to go I love having it in, but I'd like to keep `lazy_static` and `once_cell::sync::Lazy` for a while, to avoid breaking changes for now and to give some time window for projects to migrate.

**Comment by atezet** [comment]
I reverted the formatting changes and split the PR in logical commits that only changes docs and examples and adds a test for `LazyLock`. In #164 I also included a commit that uses `LazyLock` in `nutype_macros`, which I think would be acceptable to include as I think it is still possible to use `lazy_static` or `once_cell` if one would want to depend on a lower Rust version, but feel free to leave that for later.

**Comment by greyblake** [comment]
@atezet Thanks you!

**Comment by zekefast** [comment]
@greyblake, @atezet You can actually start using it today already. Just feature gate on Rust version. Use 1.80 for new `LazyCell` and `LazyLock` and fallback to `lazy_static` to prior versions of Rust.

**Comment by greyblake** [comment]
@zekefast We cannot silently fallback on `lazy_static`, it needs to be explicitly within dependencies of the project that uses `nutype`.
It probably works out of the box,and swapping `lazy_static` with `LazyLock` does not require anything, but I just want to have tests in place, to make sure that  `lazy_static` still works if some users use it.

**Comment by zekefast** [comment]
> @zekefast We cannot silently fallback on lazy_static, it needs to be explicitly within dependencies of the project that uses nutype.

That's true.

**Comment by atezet** [comment]
@greyblake The tests cover that now, right? So #164 would be mergeable too?

**Pull request merged**
